### ISSUE TITLE
CC list name not being saved in the CiviCrm group

### ISSUE THREAD

**Issue by sibro** [cividesk/com.cividesk.sync.constantcontact#3]
Trying to install your addon. On both Civicrm 4.6 and 4.7 we select the CC list name from the dropdown but it is not stored.  

Since the group is not stored the cron  shows
Entity: job Action: constant_contact_sync
Summary
Finished execution of Constant Contact Sync with result: Success (a:1:{i:0;s:30:"No groups defined for synching";})
Details

Parameters parsed (and passed to API method): 
a:1:{s:7:"version";i:3;}

Full message: 
Finished execution of Constant Contact Sync with result: Success (a:1:{i:0;s:30:"No groups defined for synching";}

**Comment by nganivet** [comment]
In the custom fields, you must ensure that the CtCt list is not readonly in the custom fields group extending the group entity.

**Comment by sibro** [comment]
On both 4.6 and 4.7 went to update the Constant Contact List ID. Unchecked View Only and save. the page,  hung. From watchdog log I see CRM/Custom/Form/Field.php(117): CRM_Core_DAO::getFieldValue("CRM_Core_DAO_CustomGroup", NULL, "is_reserved", "id")

**Comment by nganivet** [comment]
sibro - sorry I am not officially supporting this extension except for my customers, so you'll have to find the issue yourself. I can tell you a number of my customers have been using it on a daily basis for more than 2 years and it works perfectly fine for them. The extension is untested on 4.7 (and probably will have issues due to changes in the settings API).
